name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  jekyll:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        uses: nielsdelestinne/jekyll-build@v0.2.0-beta
        with:
          verbose: true

      - name: Save Artifact
        uses: actions/upload-artifact@v2
        with:
          name: niedel-website
          path: _site

      - name: Deploy using FTP
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: "_site"
          remoteDir: "/public_html"
